const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.Flowchart,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{FundoMenu: 0},
	{btnComeçar: 0},
	{Toque: 0},
	{bemVindo: 0},
	{Sprite15: 0},
	{Áudio: 0},
	{Teclado: 0},
	{BG: 0},
	{fala1Urso: 0},
	{CaixadeDialogo: 0},
	{Interpolação: 0},
	{Urso: 0},
	{Matriz: 0},
	{fala2Urso: 0},
	{Sorveteiro: 0},
	{fala3S: 0},
	{CaixaDeResposta1: 0},
	{R1: 0},
	{R2: 0},
	{respostaSorveteiro: 0},
	{respUrso1: 0},
	{ControladorDeFluxograma: 0},
	{BG2: 0},
	{velha: 0},
	{f1U: 0},
	{F2U: 0},
	{F3U: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Etapa: 0},
	{gameState: 0},
	{selection: 0},
	{points: 0},
	{TYPEWRITERSPEED: 0},
	{etapa1: 0}
];

self.InstanceType = {
	FundoMenu: class extends self.ISpriteInstance {},
	btnComeçar: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	bemVindo: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	BG: class extends self.ISpriteInstance {},
	fala1Urso: class extends self.ITextInstance {},
	CaixadeDialogo: class extends self.ISpriteInstance {},
	Urso: class extends self.ISpriteInstance {},
	Matriz: class extends self.IArrayInstance {},
	fala2Urso: class extends self.ITextInstance {},
	Sorveteiro: class extends self.ISpriteInstance {},
	fala3S: class extends self.ITextInstance {},
	CaixaDeResposta1: class extends self.ISpriteInstance {},
	R1: class extends self.ISpriteInstance {},
	R2: class extends self.ISpriteInstance {},
	respostaSorveteiro: class extends self.ISpriteInstance {},
	respUrso1: class extends self.ISpriteInstance {},
	ControladorDeFluxograma: class extends self.IInstance {},
	BG2: class extends self.ISpriteInstance {},
	velha: class extends self.ISpriteInstance {},
	f1U: class extends self.ITextInstance {},
	F2U: class extends self.ITextInstance {},
	F3U: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}